name: VoteFly
version: '${project.version}'
main: dev.bunghole.votefly.VoteFly
api-version: 1.20
commands:
  votefly:
    description: Manage your vote-fly time
    usage: /<command> [check|on|off|toggle]
    aliases: [vf]
permissions:
  votefly.use:
    description: Allows using vote-fly commands
    default: true
  votefly.mod:
    description: Moderator permissions for VoteFly
    default: op
  votefly.admin:
    description: Admin permissions for VoteFly
    default: op
